name: render_dart_backend
description: A simple Dart backend using Shelf.
version: 1.0.0

environment:
  sdk: "3.5.4"

dependencies:
  shelf: 1.4.2
  shelf_static: 1.1.3
  shelf_router: 1.1.4
  jose: 0.3.4
  http: 1.2.2
